name: project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  intl: ^0.19.0 # â­ PACKAGE ADDED
  image_picker: ^1.0.7
  video_player: ^2.8.2
  path_provider: ^2.1.1
  video_thumbnail: 0.5.3
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  camera: ^0.11.0+1
  permission_handler: ^11.0.1
  photo_manager: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"   # <-- this is color, not file
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/icons/
    - assets/reels/
    - assets/fonts/
    - assets/highlights/
    - assets/reel_icons/


  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/FontsFree-Net-Billabong.ttf
